### ISSUE TITLE
files not found

### ISSUE THREAD

**Issue by 12-zhx** [cvqluu/MTL-Speaker-Embeddings#1]
where is the vox1_meta.csv, vox2_meta.csv and vggface2_meta.csv in the python file "scrape_nationalities.py" ?

**Comment by cvqluu** [comment]
Hi, these are meta information files relating to voxceleb 1 and 2.

I have not included information on how exactly to obtain these since it seems like the voxceleb website itself has removed this information for some reason, and respecting that I have not attached these files.

However, the filenames can be searched for if you are looking for these files still. The original filenames are the same for `vox1_meta.csv` and `vox2_meta.csv`. 

However, the original filename of`vggface2_meta.csv` is `identity_meta.csv`, found in the VGGFace2 dataset.

**Comment by cvqluu** [comment]
Added extra comments within the script
